import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppDataProvider } from '@lib';
import { Menu } from '@components'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppDataProvider>
          <Menu />

          <div className="content-container">
            {children}
          </div>
        </AppDataProvider>
      </body>
    </html>
  );
}